In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
ds = pd.Series([2,4,6,8,10])
print(ds)

0     2
1     4
2     6
3     8
4    10
dtype: int64

In [4]:
ds = pd.Series([2,4,6,8,10])
print("pandas series and type")
print(ds)

print(type(ds))

print("pandas series as list")
print(ds.tolist())

print(type(ds.tolist()))

pandas series and type
0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>
pandas series as list
[2, 4, 6, 8, 10]
<class 'list'>

In [5]:
s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1,3,5,7,9])

s = s1 * s2
print(s)

s = s1 + s2
print(s)

s = s1 - s2
print(s)

s = s1 / s2
print(s)

0     2
1    12
2    30
3    56
4    90
dtype: int64
0     3
1     7
2    11
3    15
4    19
dtype: int64
0    1
1    1
2    1
3    1
4    1
dtype: int64
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

In [6]:
data = {
    'apple':[3,2,0,1],
    'oranges':[0,3,7,2]
}

purchases = pd.DataFrame(data)

print(purchases)

   apple  oranges
0      3        0
1      2        3
2      0        7
3      1        2

In [7]:
orders=pd.read_table('https://bit.ly/chiporders')
orders.head(5)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [8]:
movie=pd.read_table('https://bit.ly/movieusers',sep='|',header=None)
movie.head(5)

   0   1  2           3      4
0  1  24  M  technician  85711
1  2  53  F       other  94043
2  3  23  M      writer  32067
3  4  24  M  technician  43537
4  5  33  F       other  15213