<a href="https://colab.research.google.com/github/RamMohanHota/ML-and-PYTHON-LAB/blob/main/_10_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
players = pd.read_csv('players_22@fifa.csv')
players.head()

/tmp/ipykernel_5986/4291481403.py:1: DtypeWarning: Columns (25,108) have mixed types. Specify dtype option on import or set low_memory=False.
  players = pd.read_csv('players_22@fifa.csv')

,sofifa_id,player_url,short_name,long_name,player_positions,overall,potential,value_eur,wage_eur,age,...,lcb,cb,rcb,rb,gk,player_face_url,club_logo_url,club_flag_url,nation_logo_url,nation_flag_url
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,"RW, ST, CF",93,93,78000000.0,320000.0,34,...,50+3,50+3,50+3,61+3,19+3,https://cdn.sofifa.net/players/158/023/22_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,https://cdn.sofifa.net/teams/1369/60.png,https://cdn.sofifa.net/flags/ar.png
1,188545,https://sofifa.com/player/188545/robert-lewand...,R. Lewandowski,Robert Lewandowski,ST,92,92,119500000.0,270000.0,32,...,60+3,60+3,60+3,61+3,19+3,https://cdn.sofifa.net/players/188/545/22_120.png,https://cdn.sofifa.net/teams/21/60.png,https://cdn.sofifa.net/flags/de.png,https://cdn.sofifa.net/teams/1353/60.png,https://cdn.sofifa.net/flags/pl.png
2,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,"ST, LW",91,91,45000000.0,270000.0,36,...,53+3,53+3,53+3,60+3,20+3,https://cdn.sofifa.net/players/020/801/22_120.png,https://cdn.sofifa.net/teams/11/60.png,https://cdn.sofifa.net/flags/gb-eng.png,https://cdn.sofifa.net/teams/1354/60.png,https://cdn.sofifa.net/flags/pt.png
3,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Júnior,"LW, CAM",91,91,129000000.0,270000.0,29,...,50+3,50+3,50+3,62+3,20+3,https://cdn.sofifa.net/players/190/871/22_120.png,https://cdn.sofifa.net/teams/73/60.png,https://cdn.sofifa.net/flags/fr.png,NaN,https://cdn.sofifa.net/flags/br.png
4,192985,https://sofifa.com/player/192985/kevin-de-bruy...,K. De Bruyne,Kevin De Bruyne,"CM, CAM",91,91,125500000.0,350000.0,30,...,69+3,69+3,69+3,75+3,21+3,https://cdn.sofifa.net/players/192/985/22_120.png,https://cdn.sofifa.net/teams/10/60.png,https://cdn.sofifa.net/flags/gb-eng.png,https://cdn.sofifa.net/teams/1325/60.png,https://cdn.sofifa.net/flags/be.png

In [3]:
features=["overall","potential","wage_eur","value_eur","age"]

In [4]:
players=players.dropna(subset=features)

In [5]:
players[features] = ((players[features] - players[features].min())/(players[features].max()-players[features].min()))*10+1

In [6]:
players.describe()

,sofifa_id,overall,potential,value_eur,wage_eur,age,height_cm,weight_kg,club_team_id,league_level,...,mentality_composure,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,goalkeeping_speed
count,19165.000000,19165.000000,19165.000000,19165.000000,19165.000000,19165.000000,19165.000000,19165.000000,19165.000000,19165.000000,...,19165.000000,19165.000000,19165.000000,19165.000000,19165.000000,19165.000000,19165.000000,19165.000000,19165.000000,2124.000000
mean,231583.648526,5.078302,5.799998,1.146473,1.243826,4.403716,181.290008,74.930342,50540.725228,1.354239,...,57.899713,46.583459,48.038664,45.897156,16.401565,16.190347,16.052961,16.225098,16.489903,36.439266
std,26833.429325,1.496262,1.323418,0.392477,0.557253,1.750932,6.862654,7.066639,54398.739305,0.747572,...,12.157264,20.201097,21.226869,20.749324,17.566193,16.834231,16.560291,17.053315,17.878079,10.750788
min,41.000000,1.000000,1.000000,1.000000,1.000000,1.000000,155.000000,49.000000,1.000000,1.000000,...,12.000000,4.000000,5.000000,5.000000,2.000000,2.000000,2.000000,2.000000,2.000000,15.000000
25%,214611.000000,4.043478,4.913043,1.024022,1.014306,2.851852,176.000000,70.000000,479.000000,1.000000,...,50.000000,29.000000,28.000000,25.000000,8.000000,8.000000,8.000000,8.000000,8.000000,27.000000
50%,236586.000000,5.130435,5.782609,1.049796,1.071531,4.333333,181.000000,75.000000,1938.000000,1.000000,...,59.000000,52.000000,56.000000,53.000000,11.000000,11.000000,11.000000,11.000000,11.000000,36.000000
75%,253568.000000,6.000000,6.652174,1.102634,1.214592,5.814815,186.000000,80.000000,111139.000000,1.000000,...,66.000000,63.000000,65.000000,63.000000,14.000000,14.000000,14.000000,14.000000,14.000000,45.000000
max,264640.000000,11.000000,11.000000,11.000000,11.000000,11.000000,206.000000,110.000000,115820.000000,5.000000,...,96.000000,93.000000,93.000000,92.000000,91.000000,92.000000,93.000000,92.000000,90.000000,65.000000

In [7]:
def random_centroids(data,k):
  n_samples,n_features=data.shape
  random_sample_idxs=np.random.choice(n_samples,k,replace=False)
  centroids=[]
  for i in random_sample_idxs:
    centroid=data.iloc[i]
    centroids.append(centroid)
  centroids=pd.concat(centroids,axis=1)
  cluster_no=[id for id in range(k)]
  centroids.columns=cluster_no
  return centroids

In [8]:
def random_centroids(data,k):
  centroids=[]
  for i in range(k):
    centroid=data.apply(lambda x: float(x.sample()))
    print(centroid)
    centroids.append(centroid)
  return centroids

In [9]:
def get_labels(data, centroids):
    distances = centroids.apply(lambda x: np.sqrt(((data - x) ** 2).sum(axis=1)))
    labels = distances.idxmin(axis=1)
    return labels

In [10]:
def random_centroids(data,k):
  numeric_data = data.select_dtypes(include=np.number) # Select only numeric columns
  n_samples,n_features=numeric_data.shape
  if n_samples < k:
      raise ValueError("Number of samples in data is less than k")
  random_sample_idxs=np.random.choice(n_samples,k,replace=False)
  centroids = numeric_data.iloc[random_sample_idxs].T # Sample rows and transpose
  cluster_no=[id for id in range(k)]
  centroids.columns=cluster_no
  return centroids

In [11]:
def new_centroids(data,labels,k):
  centroids=data.groupby(labels).apply(lambda x: np.exp(np.log(x).mean())).T
  return centroids

In [12]:
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
from IPython.display import clear_output

In [13]:
def plot_clusters(data,labels,centroids,iteration):
  pca=PCA(n_components=2)
  data_2d=pca.fit_transform(data)
  centroids_2d=pca.transform(centroids.T)
  clear_output(wait=True)
  plt.title(f'Iteration {iteration}')
  plt.scatter(x=data_2d[:,0],y=data_2d[:,1],c=labels)
  plt.scatter(x=centroids_2d[:,0],y=centroids_2d[:,1])
  plt.show()